#
# Travis CI configuration
#
# Simply tests that Home Assistant configuration is valid.
#
# @link https://home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

language: python
cache: pip
python:
  - "3.7"
install:
  - sudo apt-get install -y python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
  - pip3 install homeassistant
script:
  - mv secrets-dummy.yaml secrets.yaml
  - touch fullchain.pem
  - touch privkey.pem
  - hass -c . --script check_config
