- id: door_opened
  alias: Door Opened
  trigger:
  - platform: state
    from: "off"
    to: "on"
    for:
      seconds: 1
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_inside_door
    - binary_sensor.garage_outdoor_door
    - binary_sensor.guest_door
    - binary_sensor.new_gate_opened
    - binary_sensor.old_gate_opened
    - binary_sensor.back_bedroom_window
    - binary_sensor.dining_room_window
    - binary_sensor.entrance_window
    - binary_sensor.front_bedroom_window
    - binary_sensor.laundry_room_window
    - binary_sensor.living_room_window
    - binary_sensor.master_bathroom_window
    - binary_sensor.master_bedroom_window
    - binary_sensor.office_window
    - binary_sensor.stairway_window
  - platform: state
    from: closed
    to: open
    entity_id: cover.garage_door_opener
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been opened'
    service: notify.phones
- id: door_closed
  alias: Door Closed
  trigger:
  - platform: state
    from: "on"
    to: "off"
    for:
      seconds: 1
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_inside_door
    - binary_sensor.garage_outdoor_door
    - binary_sensor.guest_door
    - binary_sensor.new_gate_opened
    - binary_sensor.old_gate_opened
    - binary_sensor.back_bedroom_window
    - binary_sensor.dining_room_window
    - binary_sensor.entrance_window
    - binary_sensor.front_bedroom_window
    - binary_sensor.laundry_room_window
    - binary_sensor.living_room_window
    - binary_sensor.master_bathroom_window
    - binary_sensor.master_bedroom_window
    - binary_sensor.office_window
    - binary_sensor.stairway_window
  - platform: state
    from: closed
    to: open
    entity_id: cover.garage_door_opener
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been closed'
    service: notify.phones

- id: door_left_open
  alias: Door is still open
  trigger:
  - platform: state
    from: "off"
    to: "on"
    for:
      minutes: 5
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_outside_door
    - binary_sensor.old_gate_opened
    - binary_sensor.new_gate_opened
  - platform: state
    from: closed
    to: open
    for:
      minutes: 5
    entity_id: cover.garage_door_opener
  action:
  - data_template:
      message: "\U0001F514 The {{ trigger.to_state.attributes.friendly_name }} is still open"
    service: notify.phones


- id: entrance_door_light_on
  alias: Turn on entrance light
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: "on"
  action:
    service: light.turn_on
    data:
      entity_id: light.entrance_light
- id: entrance_door_light_off
  alias: Turn off entrance light
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: "off"
    for:
      seconds: 60
  action:
    service: light.turn_off
    data:
      entity_id: light.entrance_light
- id: garage_door_light_on
  alias: Turn on stairway light
  trigger:
    platform: state
    entity_id: binary_sensor.garage_inside_door
    to: "on"
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: switch.downstairs_light
  - service: light.turn_on
    data:
      entity_id: light.downstairs_entrance
- id: garage_door_light_off
  alias: Turn off stairway light
  trigger:
    platform: state
    entity_id: binary_sensor.garage_inside_door
    to: "off"
    for:
      seconds: 60
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.downstairs_light
  - service: light.turn_off
    data:
      entity_id: light.downstairs_entrance

# Alarms

- alias: 'Activate alarm when away'
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.blink_sync
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm

- alias: 'Deactivate alarm when home'
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.blink_sync
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
