- id: door_opened
  alias: Door Opened
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    for:
      seconds: 3
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_inside_door
    - binary_sensor.garage_outside_door
    - binary_sensor.guest_door
    - binary_sensor.new_gate_contact
    - binary_sensor.old_gate_contact
    - binary_sensor.back_bedroom_window
    - binary_sensor.dining_room_window
    - binary_sensor.entrance_window
    - binary_sensor.front_bedroom_window
    - binary_sensor.laundry_room_window
    - binary_sensor.living_room_window
    - binary_sensor.master_bathroom_window
    - binary_sensor.master_bedroom_window
    - binary_sensor.office_window
    - binary_sensor.stairway_window
  - platform: state
    to: open
    entity_id: cover.garage_door_opener
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been opened'
    service: notify.phones
- id: door_closed
  alias: Door Closed
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for:
      seconds: 3
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_inside_door
    - binary_sensor.garage_outdoor_door
    - binary_sensor.guest_door
    - binary_sensor.new_gate_contact
    - binary_sensor.old_gate_contact
    - binary_sensor.back_bedroom_window
    - binary_sensor.dining_room_window
    - binary_sensor.entrance_window
    - binary_sensor.front_bedroom_window
    - binary_sensor.laundry_room_window
    - binary_sensor.living_room_window
    - binary_sensor.master_bathroom_window
    - binary_sensor.master_bedroom_window
    - binary_sensor.office_window
    - binary_sensor.stairway_window
  - platform: state
    to: closed
    entity_id: cover.garage_door_opener
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been closed'
    service: notify.phones
- id: door_left_open
  alias: Door is still open
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    for:
      minutes: 5
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_outside_door
    - binary_sensor.old_gate_contact
    - binary_sensor.new_gate_contact
  - platform: state
    to: open
    for:
      minutes: 5
    entity_id: cover.garage_door_opener
  action:
  - data_template:
      message: 🔔 The {{ trigger.to_state.attributes.friendly_name }} is still open
    service: notify.phones
- id: autoclose_garage_door
  alias: Autoclose Garage Door
  trigger:
  - platform: state
    to: open
    for:
      minutes: 6
    entity_id: cover.garage_door_opener
  action:
  - entity_id: cover.garage_door_opener
    service: cover.close_cover
- id: entrance_door_light_on
  alias: Turn on entrance light
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.front_foyer_main_lights
- id: entrance_door_light_off
  alias: Turn off entrance light
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: 'off'
    for:
      seconds: 60
  action:
    service: light.turn_off
    data:
      entity_id: light.front_foyer_main_lights
- id: garage_door_light_on
  alias: Turn on stairway light
  trigger:
    platform: state
    entity_id: binary_sensor.garage_inside_door
    to: 'on'
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: switch.downstairs_main_lights
  - service: light.turn_on
    data:
      entity_id: light.garage_entry_main_lights
  - service: light.turn_on
    data:
      entity_id: light.downstairs_hallway_main_lights
- id: garage_door_light_off
  alias: Turn off stairway light
  trigger:
    platform: state
    entity_id: binary_sensor.garage_inside_door
    to: 'off'
    for:
      seconds: 60
  action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.downstairs_main_lights
  - service: light.turn_off
    data:
      entity_id: light.garage_entry_main_lights
  - service: light.turn_off
    data:
      entity_id: light.downstairs_hallway_main_lights
- id: entrance_lights_when_motion
  alias: Turn on outside lights with camera motion
  trigger:
    platform: state
    entity_id: binary_sensor.front_camera_motion
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.front_porch_overhead_light
  - service: light.turn_on
    data:
      entity_id: light.front_porch_sconces
- id: entrance_lights_without_motion
  alias: Turn off outside lights without camera motion
  trigger:
    platform: state
    entity_id: binary_sensor.front_camera_motion
    to: 'off'
    for:
      minutes: 3
  action:
  - service: light.turn_off
    data:
      entity_id: light.front_porch_overhead_light
  - service: light.turn_off
    data:
      entity_id: light.front_porch_sconces
- id: leave_home
  alias: Leaving Home
  trigger:
  - platform: state
    entity_id: group.devices
    to: not_home
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.blink_home
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm
  - service: light.turn_off
    entity_id: all
- id: arrive_home
  alias: Coming Home
  trigger:
  - platform: state
    entity_id: group.devices
    to: home
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.blink_home
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm
  mode: single
- id: arrive_home_paul
  alias: Paul Comming Home
  trigger:
  - platform: state
    entity_id: device_tracker.pt_ping
    to: home
  action:
  - service: light.turn_on
    entity_id: light.front_porch_overhead_light
  - service: light.turn_on
    entity_id: light.front_porch_sconces
- id: arrive_home_and_stay_paul
  alias: Coming Home And Stay
  trigger:
  - platform: state
    entity_id: device_tracker.pt_ping
    to: home
    for: 0:05:00
  action:
  - service: light.turn_off
    entity_id: light.front_porch_overhead_light
  - service: light.turn_off
    entity_id: light.front_porch_sconces
  mode: single
- id: alarm_triggered
  alias: Alarm Triggered
  trigger:
    platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  action:
  - data_template:
      message: 🔔 🔔 🔔 The alarm is going off
    service: notify.phones
- id: binds_open
  alias: Main Floor Blinds Open
  trigger:
    platform: time
    at: 09:00:00
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: cover.open_cover
    entity_id: cover.living_room_left_big_shade
  - service: cover.open_cover
    entity_id: cover.living_room_right_big_shade
  - service: cover.open_cover
    entity_id: cover.living_room_kichen_shade
  - service: cover.open_cover
    entity_id: cover.living_room_tv_shade
  - service: cover.open_cover
    entity_id: cover.office_entrance_shade
  - service: cover.open_cover
    entity_id: cover.office_view_shade
- id: master_bedroom_binds_open
  alias: Master Bedroom Blinds Open
  trigger:
    platform: time
    at: '10:00:00'
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - thu
    - fri
  action:
  - service: cover.open_cover
    entity_id: cover.master_bedroom_left_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_right_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_michelle_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_paul_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_bathroom_shade
- id: weekend_binds_open
  alias: Weekend Blinds Open
  trigger:
    platform: time
    at: '11:00:00'
  condition:
    condition: time
    weekday:
    - sat
    - sun
  action:
  - service: cover.open_cover
    entity_id: cover.living_room_left_big_shade
  - service: cover.open_cover
    entity_id: cover.living_room_right_big_shade
  - service: cover.open_cover
    entity_id: cover.living_room_kichen_shade
  - service: cover.open_cover
    entity_id: cover.living_room_tv_shade
  - service: cover.open_cover
    entity_id: cover.office_entrance_shade
  - service: cover.open_cover
    entity_id: cover.office_side_shade
  - service: cover.open_cover
    entity_id: cover.office_view_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_left_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_right_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_michelle_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_paul_shade
  - service: cover.open_cover
    entity_id: cover.master_bedroom_bathroom_shade
- id: sunset_close_blinds
  alias: Sunset Close Blinds
  trigger:
    platform: sun
    event: sunset
  action:
  - service: cover.close_cover
    entity_id: cover.living_room_left_big_shade
  - service: cover.close_cover
    entity_id: cover.living_room_right_big_shade
  - service: cover.close_cover
    entity_id: cover.living_room_kichen_shade
  - service: cover.close_cover
    entity_id: cover.living_room_tv_shade
  - service: cover.close_cover
    entity_id: cover.office_entrance_shade
  - service: cover.close_cover
    entity_id: cover.office_side_shade
  - service: cover.close_cover
    entity_id: cover.office_view_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_left_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_right_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_michelle_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_paul_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_bathroom_shade
- id: sunset_close_blinds_take_2
  alias: Sunset Close Blinds Take 2
  trigger:
    platform: sun
    event: sunset
    offset: 00:02:00
  action:
  - service: cover.close_cover
    entity_id: cover.living_room_left_big_shade
  - service: cover.close_cover
    entity_id: cover.living_room_right_big_shade
  - service: cover.close_cover
    entity_id: cover.living_room_kichen_shade
  - service: cover.close_cover
    entity_id: cover.living_room_tv_shade
  - service: cover.close_cover
    entity_id: cover.office_entrance_shade
  - service: cover.close_cover
    entity_id: cover.office_side_shade
  - service: cover.close_cover
    entity_id: cover.office_view_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_left_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_right_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_michelle_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_paul_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_bathroom_shade
- id: master_bedroom_binds_close_hot
  alias: Master Bedroom Blinds Close On Hot Days
  trigger:
    platform: time
    at: '14:00:00'
  condition:
  - condition: template
    value_template: '{{ state_attr(''weather.home'', ''temperature'') | int > 75}}'
  action:
  - service: cover.close_cover
    entity_id: cover.master_bedroom_left_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_right_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_michelle_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_paul_shade
  - service: cover.close_cover
    entity_id: cover.master_bedroom_bathroom_shade
- id: nighttime_lights_off
  alias: Nightime Lights Off
  trigger:
    platform: time
    at: 03:00:00
  action:
  - service: light.turn_off
    entity_id: all
- id: kelsi_fan_on
  alias: Kelsi Fan On
  trigger:
    platform: time
    at: '20:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.kelsis_fan
- id: kelsi_fan_off
  alias: Kelsi Fan Off
  trigger:
    platform: time
    at: 05:00:00
  action:
  - service: switch.turn_off
    entity_id: switch.kelsis_fan
- id: tv_on
  alias: Turn TV off when idle
  trigger:
  - platform: state
    to: idle
    for:
      seconds: 5
    entity_id:
    - media_player.man_cave_tv
    - media_player.living_room_tv
    - media_player.master_bedroom_tv
    - media_player.lg_webos_smart_tv
  action:
  - service: media_player.turn_off
    data_template:
      entity_id: '{{ trigger.to_state.entity_id }}'
- id: letsencrypt_renewal
  alias: Let's Encrypt Renewal
  trigger:
  - platform: time
    at: 00:00:00
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
- id: snoo
  alias: Snoo
  trigger:
  - platform: state
    from: 'Soothing'
    to: 'Awake'
    entity_id:
    - sensor.snoo_state
  action:
  - data_template:
      message: 'Everett needs you'
    service: notify.mobile_app_michelle_iphone
