- id: door_opened
  alias: Door Opened
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    for:
      seconds: 1
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_inside_door
    - binary_sensor.garage_outdoor_door
    - binary_sensor.guest_door
  - platform: state
    from: 'closed'
    to: 'open'
    entity_id: cover.garage_door_opener
  condition: []
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been opened'
    service: notify.phones

- id: door_closed
  alias: Door Closed
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for:
      seconds: 1
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.back_door
    - binary_sensor.garage_inside_door
    - binary_sensor.garage_outdoor_door
    - binary_sensor.guest_door
  - platform: state
    from: 'closed'
    to: 'open'
    entity_id: cover.garage_door_opener
  condition: []
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been closed'
    service: notify.phones

- id: window_opened
  alias: Window Opened
  trigger:
    from: 'off'
    platform: state
    to: 'on'
    entity_id:
    - binary_sensor.back_bedroom_window
    - binary_sensor.dining_room_window
    - binary_sensor.entrance_window
    - binary_sensor.front_bedroom_window
    - binary_sensor.laundry_room_window
    - binary_sensor.living_room_window
    - binary_sensor.master_bathroom_window
    - binary_sensor.master_bedroom_window
    - binary_sensor.office_window
    - binary_sensor.stairway_window
  condition: []
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been opened'
    service: notify.phones

- id: window_closed
  alias: Window Closed
  trigger:
    from: 'on'
    platform: state
    to: 'off'
    entity_id:
    - binary_sensor.back_bedroom_window
    - binary_sensor.dining_room_window
    - binary_sensor.entrance_window
    - binary_sensor.front_bedroom_window
    - binary_sensor.laundry_room_window
    - binary_sensor.living_room_window
    - binary_sensor.master_bathroom_window
    - binary_sensor.master_bedroom_window
    - binary_sensor.office_window
    - binary_sensor.stairway_window
  condition: []
  action:
  - data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} has been closed'
    service: notify.phones

- id: entrance_door_light_on
  alias: Turn on entrance light when front door opens
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.entrance_light

- id: entrance_door_light_off
  alias: Turn off entrance light after 1 min of door closed
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    to: 'off'
    for:
      seconds: 60
  action:
    service: light.turn_off
    data:
      entity_id: light.entrance_light

- id: garage_door_light_on
  alias: Turn on stairway light when the inside garage door opens
  trigger:
    platform: state
    entity_id: binary_sensor.garage_inside_door
    to: 'on'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.downstairs_light
    - service: light.turn_on
      data:
        entity_id: light.downstairs_entrance

- id: garage_door_light_off
  alias: Turn off stairway light after 1 min of door closed
  trigger:
    platform: state
    entity_id: binary_sensor.garage_inside_door
    to: 'off'
    for:
      seconds: 60
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: switch.downstairs_light
    - service: light.turn_off
      data:
        entity_id: light.downstairs_entrance

- id: garage_door_left_open
  alias: Garage door is still open
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    from: 'closed'
    to: 'open'
    for:
      minutes: 5
  action:
    service: notify.phones
    data:
      message: The garage door is still open

- id: front_door_left_open
  alias: Front door is still open
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'closed'
    to: 'open'
    for:
      minutes: 5
  action:
    service: notify.phones
    data:
      message: The front door is still open

- id: garage_little_door_left_open
  alias: Garage little door is still open
  trigger:
    platform: state
    entity_id: binary_sensor.garage_outside_door
    from: 'closed'
    to: 'open'
    for:
      minutes: 5
  action:
    service: notify.phones
    data:
      message: The little garage door is still open
