homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  base_url: https://home.paulisageek.com:8123
  ssl_certificate: !secret ssl_fullchain
  ssl_key: !secret ssl_privkey
    
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


# Cloud
# cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

wink:

envisalink:
  host: 192.168.1.19
  panel_type: DSC
  user_name: user
  password: !secret envisalink_password
  code: !secret envisalink_code
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  panic_type: Police
  zones:
    01:
      name: 'Front Door'
      type: 'door'
    02:
      name: 'Front Door Motion'
      type: 'motion'
    03:
      name: 'Upstairs Motion'
      type: 'motion'
    04:
      name: 'Dining Room Window'
      type: 'window'
    05:
      name: 'Living Room Window'
      type: 'window'
    06:
      name: 'Guest Room'
      type: 'window'
    07:
      name: 'Office Window'
      type: 'window'
    08:
      name: 'Guest Door'
      type: 'door'
    09:
      name: 'Laundry Room Window'
      type: 'window'
    10:
      name: 'Stairway Window'
      type: 'window'
    11:
      name: 'Back Bedroom Window'
      type: 'window'
    12:
      name: 'Front Bedroom Window'
      type: 'window'
    13:
      name: 'Master Bedroom Window'
      type: 'window'
    14:
      name: 'Master Bathroom Window'
      type: 'window'
    15:
      name: 'Garage Inside Door'
      type: 'door'
    16:
      name: 'Garage Outdoor Door'
      type: 'door'
    17:
      name: 'Unknown 17'
      type: 'motion'
    18:
      name: 'Entrance Window'
      type: 'window'
    19:
      name: 'Back Door'
      type: 'door'
  partitions:
    1:
      name: 'Home Alarm'

media_player:
  - platform: plex
  - platform: webostv
    host: 192.168.1.162
  - platform: denon
    host: 192.168.1.171

roku:
  - host: 192.168.1.163
  - host: 192.168.1.164
  
wemo:

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Sound Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Silence Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'textInput'
            textInputButtonTitle: 'Silencio!'
            textInputPlaceholder: 'Placeholder'

binary_sensor:
  - platform: hikvision
    host: 192.168.1.14
    port: 80
    ssl: False
    username: admin
    password: !secret hikvision_password
  - platform: ring

sensor:
  - platform: ring
      
camera:
  - platform: generic
    name: Driveway
    still_image_url: http://192.168.1.14/ISAPI/Streaming/channels/101/picture
    username: admin
    password: !secret hikvision_password
  - platform: generic
    name: Entrance
    still_image_url: http://192.168.1.14/ISAPI/Streaming/channels/201/picture
    username: admin
    password: !secret hikvision_password
  - platform: generic
    name: Side
    still_image_url: http://192.168.1.14/ISAPI/Streaming/channels/301/picture
    username: admin
    password: !secret hikvision_password
  - platform: generic
    name: Back
    still_image_url: http://192.168.1.14/ISAPI/Streaming/channels/401/picture
    username: admin
    password: !secret hikvision_password

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: chamberlain

notify:
  - name: phones
    platform: group
    services:
      - service: ios_pt
      - service: ios_michelles_iphone

nest:
    client_id: !secret nest_id
    client_secret: !secret nest_secret

rachio:
    api_key: !secret rachio_api_key

blink:
    username: !secret blink_username
    password: !secret blink_password

ring:
    username: !secret ring_username
    password: !secret ring_password

device_tracker:
  - platform: ping
    hosts:
      pt_ping: 192.168.1.110
      michelle_ping: 192.168.1.111
    consider_home: 600


# mqtt:

# upnp:

switch:
#  - platform: hikvisioncam
#    host: 192.168.1.10
#  - platform: hikvisioncam
#    host: 192.168.1.11
#  - platform: hikvisioncam
#    host: 192.168.1.12
#  - platform: hikvisioncam
#    host: 192.168.1.13
#  - platform: tplink
#    host: 192.168.1.237

#bmw_connected_drive:
#  name:
#    username: !secret bmw_username
#    password: !secret bmw_password
#    country: USA

# homekit:

system_health:

google_assistant:
  project_id: paul-s-home-assistant
  api_key: !secret google_assistant_api_key
  entity_config:
    climate.main_floor:
      expose: false
    climate.upstairs:
      expose: false
    cover.all_shades:
      expose: false
    cover.garage_door_opener_2:
      expose: false
    cover.living_room_shades:
      expose: false
    cover.master_bedroom_shades:
      expose: false
    cover.office_shades:
      expose: false
    group.all_automations:
      expose: false
    group.all_covers:
      expose: false
    group.all_devices:
      expose: false
    group.all_lights:
      expose: false
    group.all_remotes:
      expose: false
    group.all_switches:
      expose: false
    light.downstairs:
      expose: false
    light.kitchen:
      expose: false
    light.living_room:
      expose: false
    light.main_floor:
      expose: false
    light.master:
      expose: false
    light.outside:
      expose: false
    light.upstairs:
      expose: false
    scene.all_lights_off:
      expose: false
    scene.all_shades_close:
      expose: false
    scene.all_shades_open:
      expose: false
    scene.come_home:
      expose: false
    scene.living_room_shades_close:
      expose: false
    scene.living_room_shades_open:
      expose: false
    scene.master_bedroom_shades_close:
      expose: false
    scene.master_bedroom_shades_open:
      expose: false
    scene.movie_time:
      expose: false
    scene.office_shades_close:
      expose: false
    scene.office_shades_open:
      expose: false
    scene.tv_time:
      expose: false
